[theme]
<<<<<<< HEAD
primaryColor="#ff9966"
=======
primaryColor="1982c4"
>>>>>>> a9c36b6ec9d3069dfa991d761b00a4ff2f2af9b3
backgroundColor=""
secondaryBackgroundColor=""
textColor=""
font="sans serif"

#ff9966